/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "jyfagnhcstmcpueyeswh"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp5ZmFnbmhjc3RtY3B1ZXllc3doIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyODc2NTAsImV4cCI6MjA3Mzg2MzY1MH0.0mDvHDkGUHDO_blAbGO43Kok5z96pcKbeQy8-4Y-6j8"